### ISSUE TITLE
updation of the login button

### ISSUE THREAD

**Issue by RishitaChourey** [HartzFrequency/Unified-Travelling-and-Transport-System#28]
The registration form have no submit button for registering a new user.

**Comment by RishitaChourey** [comment]
I am a gssoc 24 contributor and i have successfully setup this project on my machine. Please assign me this issue.

**Comment by HartzFrequency** [comment]
hey @RishitaChourey 
the registration form do have submit button named as register 

![image](https://github.com/HartzFrequency/Unified-Travelling-and-Transport-System/assets/94034434/260c3761-bf38-4a69-a309-62f94f001fd0)

I'm closing the issue, you can raise another issues

**Comment by khuship23** [comment]
Hello @HartzFrequency 
I'm keen to tackle this issue leveraging my frontend experience. Please assign it to me.

**Comment by vsmp47** [comment]
Heyy ! I would like to contribute to this issue as i have experience in frontend for a hackathon ! Please assign me this issue

**Comment by RishitaChourey** [comment]
@HartzFrequency  then i think it the window need to be expanded for the register to be visible.Because this is what is visible to me when i run the code
![Screenshot (112)](https://github.com/HartzFrequency/Unified-Travelling-and-Transport-System/assets/128152517/73920649-6fc6-4c87-aa7b-8638330f10e5)
