### ISSUE TITLE
Updation of Requirements.txt is required 

### ISSUE THREAD

**Issue by PlanetDestroyyer** [HartzFrequency/Unified-Travelling-and-Transport-System#31]
current Requirements.txt is wrong and not in proper format it should get updated asap

tk
customtkinter
pillow
mysql-connector-python

this is not correct format

**Comment by HartzFrequency** [comment]
@PlanetDestroyyer the issue is already raise and assigned you can raise another issue

**Comment by PlanetDestroyyer** [comment]
> @PlanetDestroyyer the issue is already raise and assigned you can raise another issue

Ohhh sorry I was not knowing about it
