### ISSUE TITLE
Adding all_files.sql

### ISSUE THREAD

**Issue by PrajwalaY26** [HartzFrequency/Unified-Travelling-and-Transport-System#32]
For importing the utts, as there are many sql files in the DatabaseFiles directory , it would be handy and useful to add an all_files.sql file, to make the importing process easier. @HartzFrequency please assign me this issue, I am an gssoc'24 contributor and I want to work on this issue.

**Comment by HartzFrequency** [comment]
@PrajwalaY26 you can work on this issue,
remember that when giving the PR request do add screenshots of what you done, how importing affected before and after the change
the level will be assigned correspond to what you done

you can start working on this

**Comment by PrajwalaY26** [comment]
Thank you for the opportunity to work on this issue @HartzFrequency . I understand the requirements and will make sure to include screenshots demonstrating the impact of my changes when I submit my PR. I’ll start working on this right away. If I have any questions or need further clarification, I’ll be sure to ask. Thanks again!

**Comment by tejaswini4996** [comment]
as a backend dev I would love be get this issue
