### ISSUE TITLE
Code Documentaion of GUI_module

### ISSUE THREAD

**Issue by shrehs** [HartzFrequency/Unified-Travelling-and-Transport-System#36]
Issue: GUI_module files lack documentation such as inline comments, DocStrings for better code readability

About project: The project is about Unified Travelling and Transport system which provide features such as real time tracking, payment options and fare estimation.
My understanding about the project: I could relate it to the system which already exists in today's systtem UPI, I think that could be part where the idea could be generated. Able to document the code would make it easier to contributors to contribute much easier.

I believe I could work on this issue. Please consider my request to be assigned to this issue Thank you.

**Comment by HartzFrequency** [comment]
@shrehs you can work on it, note that the documentation should be relevant and will be checked before merging and wouldn't be merged until it's relevant, level of pr will depend on the documentation

**Comment by shrehs** [comment]
Sure, if you could assign it above that would be great. Thank you!

**Comment by shrehs** [comment]
Hi! I hope this finds you well,
 I have done documentation of Aeroplane-Home-page : "https://github.com/HartzFrequency/Unified-Travelling-and-Transport-System/pull/49". If you could give me review on this I could move forward with the other files. Thank you!

**Comment by shrehs** [comment]
Hi, I hope this finds you well. It would be great if you could review this as the PR is done over 3 weeks. 
Thank you very much!
