### ISSUE TITLE
 Request to Add Payments, Bookings History, Feedback & Reviews to Database File

### ISSUE THREAD

**Issue by Shubhanshu-356** [HartzFrequency/Unified-Travelling-and-Transport-System#69]
Dear HartzFrequency,

I hope you're doing well. I wanted to discuss the addition of some crucial database files to this unified traveling and transport system. These additions will significantly enhance our system's functionality and improve user experience.

1. Payments:
Database File: payments.sql
Description: This file will handle payment transactions, including storing payment details, transaction IDs, and related information.
Bookings History:

2.Database File: bookings_history.sql
Description: This file will track the history of bookings made by users, providing insights into past travel patterns and preferences.
Feedback and Reviews:

3.Database File: feedback_reviews.sql
Description: This file will manage user feedback and reviews for different transportation modes and routes, helping improve service quality and user experience.
Assign me this issue I surely work on it.
Thank You

**Comment by Shubhanshu-356** [comment]
Assign me this issue I will surely work on it.

**Comment by HartzFrequency** [comment]
@Shubhanshu-356 I am migrating the entire database from sql to MongoDb so there is no need for creating new sql files, however you can raise new issues.

**Comment by Shubhanshu-356** [comment]
Ok thanks for the info. I will raise further new issue.
