### ISSUE TITLE
Update the way to install dependencies in README

### ISSUE THREAD

**Issue by Vikranth3140** [HartzFrequency/Unified-Travelling-and-Transport-System#85]
The README is not updated to `pip install -r requirements.txt` even though the requirements.txt file has been added.

**Comment by Shubham-Zone** [comment]
@HartzFrequency please assign this to me i am GSSOC'24 contributor and have + years of experience in development

**Comment by Vikranth3140** [comment]
@HartzFrequency, I have already submitted a PR, please review
